### ISSUE TITLE
Текущий активный курс по ml на courcera 

### ISSUE THREAD

**Issue by nesterione** [denisbalyko/mllink#1]
Это ссылка на текущий активный курс, он уже идет неделю, но первый deadline 8 февраля
https://class.coursera.org/ml-008

и вот еще ссылку можно добавить 
http://poligon.machinelearning.ru/   (хотя она есть на http://www.machinelearning.ru/wiki )

**Comment by denisbalyko** [comment]
@nesterione так можно прямо README.md редактировать и пусть файлик нарастает новыми ссылками

**Comment by nesterione** [comment]
@denisbalyko ок, подумал нету доступа на редактирование
